"""Publication artefacts generated from the model and the graph, so they cannot drift from the code (RESEARCH_ROADMAP.md phases 11 and 13):

- `crosswalk_rows` / `crosswalk_tsv`: the shared ID table for the other AgriHub products (task 11.4): every disease, variety, gene and zone with its stable KG id, its names and the
  abbreviations the AICRP reports use for it, and empty columns for the label each other product uses (the IoT, phenomic and mobile teams fill those in).
- `data_dictionary_markdown`: entity types and their properties, claim types with their subject/object types and qualifiers, evidence methods and weights, tiers, ID formats.
- `dataset_metadata`: a schema.org Dataset description (JSON-LD) with counts, the release tag, the scoring policy and the licence field the owner has to decide.
"""

from __future__ import annotations

import csv
import io
import json
from datetime import date

import curator.model  # noqa: F401
from curator.graph.bundle import KGBundle
from curator.model import claims as claim_models
from curator.model.entities import PROPS_MODEL
from curator.model.enums import CLAIM_SIGNATURE, CROP_SCOPED, EVIDENCE_WEIGHT, ID_PREFIX, ClaimType

# Abbreviations the AICRP reports and papers use for the in-scope diseases (not in the vocabulary file, which has full names only).
DISEASE_ABBREVIATIONS = {
    "dis:soybean:charcoal_rot": ["CR"], "dis:soybean:frogeye_leaf_spot": ["FLS"], "dis:soybean:anthracnose": ["PB(CT)", "pod blight (Colletotrichum truncatum)"],
    "dis:soybean:bacterial_pustule": ["BP"], "dis:soybean:mosaic_virus": ["SMV"], "dis:soybean:rust": ["ASR", "SBR"], "dis:soybean:rhizoctonia_root_rot": ["RAB (aerial blight form)"],
    "dis:wheat:stripe_rust": ["yellow rust", "Yr"], "dis:wheat:leaf_rust": ["brown rust", "Lr"], "dis:wheat:stem_rust": ["black rust", "Sr"], "dis:wheat:powdery_mildew": ["PM"],
    "dis:wheat:fusarium_head_blight": ["FHB", "head scab"], "dis:chickpea:fusarium_wilt": ["FW", "Foc"], "dis:chickpea:dry_root_rot": ["DRR"], "dis:chickpea:collar_rot": ["CR (chickpea)"],
}
CROSSWALK_COLUMNS = ["kg_id", "type", "crop", "name", "synonyms", "report_abbreviations", "release_year", "phenomic_model_label", "iot_label", "mobile_app_label"]


def crosswalk_rows(bundle: KGBundle) -> list[dict]:
    rows = []
    for e in sorted(bundle.entities, key=lambda x: (x.type.value, x.crop.value if x.crop else "", x.name)):
        if e.type.value not in ("Disease", "Variety", "Gene", "AgroZone", "Pathogen", "Crop"):
            continue
        rows.append({"kg_id": e.id, "type": e.type.value, "crop": e.crop.value if e.crop else "", "name": e.name, "synonyms": "; ".join(e.synonyms),
                     "report_abbreviations": "; ".join(DISEASE_ABBREVIATIONS.get(e.id, [])), "release_year": e.props.get("release_year", "") if e.type.value == "Variety" else "",
                     "phenomic_model_label": "", "iot_label": "", "mobile_app_label": ""})
    return rows


def crosswalk_tsv(bundle: KGBundle) -> str:
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=CROSSWALK_COLUMNS, delimiter="\t", lineterminator="\n")
    w.writeheader()
    w.writerows(crosswalk_rows(bundle))
    return buf.getvalue()


def _fields(model) -> list[str]:
    out = []
    for name, info in model.model_fields.items():
        required = info.is_required()
        out.append(f"`{name}`{'' if required else ' (optional)'}: {str(info.annotation).replace('typing.', '').replace('<class ', '').replace('>', '').replace(chr(39), '')}")
    return out


def data_dictionary_markdown() -> str:
    L: list[str] = []
    w = L.append
    w("# Data dictionary\n")
    w("Generated by `agrihub kg publish-files` from the pydantic models in `curator/model/`; it cannot drift from the code.\n")
    w("## Identifiers\n")
    w("`<prefix>:<crop>:<local>` for crop-scoped types and `<prefix>:<local>` otherwise. Prefixes: " + ", ".join(f"{t.value} = `{p}`" for t, p in ID_PREFIX.items())
      + ". Crop-scoped types: " + ", ".join(sorted(t.value for t in CROP_SCOPED)) + ". Claim ids are content hashes (`claim:<16 hex>`) of type, subject, object and qualifiers, so the same statement always has the same id.\n")
    w("## Entity types and their properties\n")
    for etype, model in PROPS_MODEL.items():
        w(f"### {etype.value}\n")
        for f in _fields(model):
            w(f"- {f}")
        w("")
    w("## Claim types\n")
    w("A claim is a typed, scored statement between two entities; every claim carries at least one evidence row (source, method, locator, verbatim quote, extractor).\n")
    for ctype in ClaimType:
        subj, obj = CLAIM_SIGNATURE[ctype]
        w(f"### {ctype.value}\n")
        w(f"Subject: {', '.join(sorted(t.value for t in subj))}. Object: {', '.join(sorted(t.value for t in obj))}.\n")
        qmodel = claim_models.QUALIFIERS[ctype]
        fields = _fields(qmodel)
        w("Qualifiers: " + ("; ".join(fields) if fields else "none") + "\n")
    w("## Evidence methods and weights\n")
    w("| Method | Weight |\n|---|---|")
    for m, wt in sorted(EVIDENCE_WEIGHT.items(), key=lambda kv: -kv[1]):
        w(f"| {m.value} | {wt} |")
    w("\nA claim's score is `1 - prod(1 - w)` over independent sources (a source contributes its strongest evidence only); evidence found by a language model and not yet reviewed is multiplied by 0.6; "
      "evidence more than ten years old on race-structured claims by 0.8. Tiers: A >= 0.85, B >= 0.65, C >= 0.40, D below; a conflicting claim is capped at C. "
      "See `curator/graph/scoring.py` and `docs/QC_REPORT.md` (sensitivity of the tiers to these constants).\n")
    return "\n".join(L) + "\n"


def dataset_metadata(bundle: KGBundle, *, release: str, repo_url: str = "https://github.com/KASVIK26/gkb-v1") -> dict:
    claims = bundle.claims
    return {
        "@context": "https://schema.org", "@type": "Dataset",
        "name": "AgriHub Genomic Knowledge Base: disease resistance of wheat, soybean and chickpea for Central India",
        "description": ("A scored, evidence-backed knowledge graph of crop varieties, their disease reactions, resistance genes and genome regions, pathotype surveys, weather triggers and "
                        "management advisories. Every claim cites a source with a verbatim quote; confidence tiers A-D are computed, not asserted."),
        "version": release, "dateModified": date.today().isoformat(), "url": repo_url,
        "license": "https://creativecommons.org/licenses/by/4.0/",
        "licenseNote": "Dataset (this knowledge graph) is CC BY 4.0 -- see kg/LICENSE-DATA. The software that builds and serves it (curator/, api/, functions/, public/) is MIT -- see /LICENSE. "
                       "Third-party sources that evidence rows cite or quote keep their own terms; this project reproduces only short verification excerpts, never full source documents.",
        "keywords": ["wheat", "soybean", "chickpea", "disease resistance", "knowledge graph", "India", "rust", "pathotype"],
        "variableMeasured": [f"{len(bundle.entities)} entities", f"{len(claims)} claims", f"{len(bundle.evidence)} evidence rows", f"{len(bundle.sources)} sources"],
        "measurementTechnique": "Verified quotation from open literature and official documents (parsers for tables, a verifier for outside-research candidates); AI first-pass review, no human reviewer yet",
        "isAccessibleForFree": True,
    }


def metadata_json(bundle: KGBundle, *, release: str) -> str:
    return json.dumps(dataset_metadata(bundle, release=release), indent=2, ensure_ascii=False) + "\n"
